/* tools/build-data.js — one-time build step.
 * Downloads and simplifies admin boundaries, then bundles them as classic JS
 * globals (so the app works when opened directly from disk, no fetch needed).
 *
 * Run:  node tools/build-data.js
 * Produces:
 *   data/countries.js    -> window.CountriesGeoJSON   (country polygons, ISO3)
 *   data/states.js       -> window.StatesGeoJSON      (global states/provinces)
 *   data/us-counties.js  -> window.USCountiesGeoJSON  (US counties)
 *   data/adm2.js         -> window.ADM2GeoJSON        (county-level ADM2 for a
 *                                                      starter set of countries)
 */
"use strict";
const fs = require("fs");
const path = require("path");

const TOL_KM = 2.0; // simplification tolerance
const TOL_DEG = TOL_KM / 111.0;

function simplifyRing(ring, tolDeg) {
  // Normalize to a closed ring (first point duplicated at end).
  let closed = ring;
  const opened = ring.length && (ring[0][0] !== ring[ring.length - 1][0] || ring[0][1] !== ring[ring.length - 1][1]);
  if (opened) closed = ring.concat([ring[0]]);
  if (closed.length < 4) return closed;
  const n = closed.length;
  const keep = new Uint8Array(n);
  keep[0] = keep[n - 1] = 1;
  const stack = [[0, n - 1]];
  while (stack.length) {
    const [lo, hi] = stack.pop();
    if (hi - lo < 2) continue;
    const ax = closed[lo][0], ay = closed[lo][1];
    const bx = closed[hi][0], by = closed[hi][1];
    const dxy = Math.hypot(bx - ax, by - ay);
    let maxD = -1, idx = -1;
    if (dxy < 1e-9) {
      // degenerate chord (closed ring) — keep the midpoint furthest from it
      maxD = 0;
      for (let i = lo + 1; i < hi; i++) {
        const d = Math.hypot(closed[i][0] - ax, closed[i][1] - ay);
        if (d > maxD) { maxD = d; idx = i; }
      }
    } else {
      for (let i = lo + 1; i < hi; i++) {
        const px = closed[i][0], py = closed[i][1];
        const d = Math.abs((px - ax) * (by - ay) - (py - ay) * (bx - ax)) / dxy;
        if (d > maxD) { maxD = d; idx = i; }
      }
    }
    if (maxD > tolDeg && idx > 0) {
      keep[idx] = 1;
      stack.push([lo, idx], [idx, hi]);
    }
  }
  const out = [];
  for (let i = 0; i < n; i++) if (keep[i]) out.push(closed[i]);
  return out;
}

function simplifyGeometry(geom, tolDeg) {
  if (!geom) return null;
  if (geom.type === "Polygon") {
    const rings = geom.coordinates.map(r => simplifyRing(r, tolDeg)).filter(r => r.length >= 4);
    if (!rings.length) return null;
    return { type: "Polygon", coordinates: rings };
  }
  if (geom.type === "MultiPolygon") {
    const polys = [];
    for (const poly of geom.coordinates) {
      const rings = poly.map(r => simplifyRing(r, tolDeg)).filter(r => r.length >= 4);
      if (rings.length) polys.push(rings);
    }
    if (!polys.length) return null;
    return { type: "MultiPolygon", coordinates: polys };
  }
  return geom;
}

function simplifyFeatureCollection(fc, tolDeg) {
  const feats = [];
  for (const f of fc.features) {
    if (!f.geometry) continue;
    const g = simplifyGeometry(f.geometry, tolDeg);
    if (!g) continue;
    feats.push({ type: "Feature", id: f.id != null ? f.id : undefined, properties: f.properties || {}, geometry: g });
  }
  return { type: "FeatureCollection", features: feats };
}

function writeBundle(filename, globalName, value) {
  const js = `// Generated by tools/build-data.js — do not edit.\nwindow.${globalName} = ` + JSON.stringify(value) + ";\n";
  fs.writeFileSync(path.join(__dirname, "..", "data", filename), js);
  console.log(filename, "->", (js.length / 1024 / 1024).toFixed(2), "MB");
}

async function main() {
  fs.mkdirSync(path.join(__dirname, "..", "data"), { recursive: true });

  // --- countries ---
  console.log("Fetching countries...");
  const cr = await fetch("https://raw.githubusercontent.com/datasets/geo-countries/main/data/countries.geojson");
  const countries = await cr.json();
  // This dataset stores "-99" for a few territories/entities; fix the important ones.
  const ISO3_OVERRIDES = {
    "France": "FRA", "Norway": "NOR", "Kosovo": "XKX", "Somaliland": "SOM",
    "Northern Cyprus": "CYP", "Cyprus No Mans Area": "CYP", "Siachen Glacier": "IND",
    "Baykonur Cosmodrome": "KAZ", "Bir Tawil": "SUD", "Clipperton Island": "FRA",
    "Southern Patagonian Ice Field": "CHL", "Indian Ocean Territories": "AUS",
    "Dhekelia Sovereign Base Area": "GBR", "Akrotiri Sovereign Base Area": "GBR",
    "US Naval Base Guantanamo Bay": "CUB",
  };

  // Continent per ISO3 (UN M49 continent codes), used to auto-center the map on
  // the continent where the user has the most points.
  const continentMap = new Map(); // iso3 -> continent name
  try {
    const ccText = await (await fetch("https://raw.githubusercontent.com/datasets/country-codes/master/data/country-codes.csv")).text();
    const ccLines = ccText.split(/\r?\n/);
    const ccHdr = ccLines[0].split(",");
    const ci3 = ccHdr.indexOf("ISO3166-1-Alpha-3");
    const cCol = ccHdr.indexOf("Continent");
    const CONT = { AF: "Africa", AS: "Asia", EU: "Europe", NA: "North America", OC: "Oceania", SA: "South America", AN: "Antarctica" };
    for (const l of ccLines.slice(1)) {
      if (!l.trim()) continue;
      // crude CSV parse
      const cells = []; let cur = "", inQ = false;
      for (const ch of l) {
        if (ch === '"') inQ = !inQ;
        else if (ch === "," && !inQ) { cells.push(cur); cur = ""; }
        else cur += ch;
      }
      cells.push(cur);
      const code = cells[ci3] && cells[ci3].trim();
      const cont = CONT[cells[cCol] && cells[cCol].trim()];
      if (code && cont) continentMap.set(code, cont);
    }
    console.log("  continent map:", continentMap.size, "entries");
  } catch (e) { console.warn("  continent map failed:", e.message); }

  const cFeats = countries.features.map(f => {
    const iso3 = ISO3_OVERRIDES[f.properties.name] || f.properties["ISO3166-1-Alpha-3"] || "";
    return {
      id: iso3,
      properties: { name: f.properties.name, ISO3: iso3, continent: continentMap.get(iso3) || "" },
      geometry: f.geometry,
    };
  });
  writeBundle("countries.js", "CountriesGeoJSON", simplifyFeatureCollection({ type: "FeatureCollection", features: cFeats }, TOL_DEG));

  // --- US states + counties via topojson-client ---
  const tjPath = path.join(__dirname, "topojson-client.min.js");
  if (!fs.existsSync(tjPath)) {
    console.log("Fetching topojson-client...");
    const r = await fetch("https://unpkg.com/topojson-client@3.1.0/dist/topojson-client.min.js");
    fs.writeFileSync(tjPath, await r.text());
  }
  const topojson = require(tjPath);

  console.log("Fetching US counties...");
  const kr = await fetch("https://cdn.jsdelivr.net/npm/us-atlas@3/counties-10m.json");
  const countiesTopo = await kr.json();
  const counties = topojson.feature(countiesTopo, countiesTopo.objects.counties);
  const kFeats = counties.features.map(f => {
    const sid = String(f.id).slice(0, 2);
    return {
      id: "US-" + f.id,
      properties: { name: f.properties.name, ISO3: "USA", adm: "county", stateFips: sid },
      geometry: f.geometry,
    };
  });
  writeBundle("us-counties.js", "USCountiesGeoJSON", simplifyFeatureCollection({ type: "FeatureCollection", features: kFeats }, TOL_DEG));

  // --- global ADM1 (states/provinces) from Natural Earth 10m ---
  console.log("Fetching global states (Natural Earth 10m, ~60MB)…");
  const ar = await fetch("https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/10m/cultural/ne_10m_admin_1_states_provinces.json");
  const adm1 = await ar.json();
  console.log("  raw features:", adm1.features.length);
  const adm1Feats = adm1.features.map(f => {
    const p = f.properties || {};
    return {
      id: p.iso_3166_2 || (p.adm0_a3 + "-" + p.name),
      properties: { name: p.name, ISO3: p.adm0_a3 || "", adm: "state" },
      geometry: f.geometry,
    };
  });
  // coarser tolerance for the big global file
  const ADM1_TOL_DEG = (TOL_KM * 1.5) / 111.0;
  writeBundle("states.js", "StatesGeoJSON", simplifyFeatureCollection({ type: "FeatureCollection", features: adm1Feats }, ADM1_TOL_DEG));

  // --- ADM2 (county-level) for a starter set of countries, from geoBoundaries ---
  const ADM2_ISO3S = ["CAN", "GBR", "AUS", "DEU", "FRA", "JPN", "ITA", "NLD", "ESP"];
  console.log("Fetching ADM2 for:", ADM2_ISO3S.join(", "));
  const adm2Feats = [];
  for (const iso3 of ADM2_ISO3S) {
    try {
      const api = await (await fetch("https://www.geoboundaries.org/api/current/gbOpen/" + iso3 + "/ADM2/")).json();
      const item = Array.isArray(api) ? api[0] : api;
      const url = item && (item.simplifiedGeometryGeoJSON || item.gjDownloadURL);
      if (!url) { console.log("  no ADM2 url for", iso3); continue; }
      // github raw serves the LFS pointer; media.githubusercontent serves the blob.
      const mediaUrl = url
        .replace(/^https:\/\/github\.com\//, "https://media.githubusercontent.com/media/")
        .replace(/\/raw\//, "/");
      const gj = await (await fetch(mediaUrl)).json();
      const feats = (gj.features || []).map((f, i) => {
        const p = f.properties || {};
        const name = p.shapeName || p.name || (iso3 + " " + i);
        const shapeISO = p.shapeISO || (iso3 + "-" + i);
        return { id: iso3 + "-" + shapeISO, properties: { name, ISO3: iso3, adm: "county" }, geometry: f.geometry };
      });
      console.log("  ", iso3, "->", feats.length, "features");
      adm2Feats.push(...feats);
    } catch (e) { console.log("  ERR", iso3, e.message); }
  }
  writeBundle("adm2.js", "ADM2GeoJSON", simplifyFeatureCollection({ type: "FeatureCollection", features: adm2Feats }, TOL_DEG));

  console.log("Done.");
}

main().catch(e => { console.error(e); process.exit(1); });
